trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

steps:
- bash: |
    git push https://$(GITHUB_PAT)@github.com/hoooowsh/LifeRec-Categories \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'
