trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

jobs:
- job: RunBETests
  steps:
  - script: echo "Running tests..."
  - checkout: self
  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*Test/*.csproj'
      arguments: '--configuration $(BuildConfiguration)'    
    displayName: 'Run Unit Tests'

- job: PushToGithub
  displayName: 'Push To GitHub'
  condition: and(succeeded(), eq(variables['Build.Reason'], 'IndividualCI'))
  dependsOn: RunBETests
  steps:
  - script: echo "Pushing to GitHub..."
  - checkout: self
    persistCredentials: true
  - bash: |
      git clone --mirror https://dev.azure.com/LifeRec/LifeRecApp/_git/LifeRec-Categories $(build.sourcesdirectory)/LifeRec-Categories
      cd $(build.sourcesdirectory)/LifeRec-Categories
      git remote add mirror git@github.com:hoooowsh/LifeRec-Categories.git
      git push mirror --progress --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
    displayName: 'Copy to Github'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')