trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

steps:
- checkout: self
- script: |
    git config --global user.email "haosheng950403@gmail.com"
    git config --global user.name "hoooowsh"
    git remote | grep -q github || git remote add github https://github.com/hoooowsh/LifeRec-Categories.git
    echo "Adding GitHub as a remote repository"
    git push github main:main --force
  displayName: 'Push to GitHub'
  env:
    GITHUB_TOKEN: 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