trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

jobs:
- job: PushToGithub
  steps:
  - checkout: self
    persistCredentials: true
  
  - bash: |
      git clone --mirror https://dev.azure.com/LifeRec/LifeRecApp/_git/LifeRec-Categories ~/LifeRec-Categories
      cd ~/LifeRec-Categories
      git remote add mirror git@github.com:hoooowsh/LifeRec-Categories.git
      git push mirror --progress --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*
    displayName: 'Copy to Github'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')