trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

jobs:
- job: Build
  steps:
  - checkout: self
    persistCredentials: true

  - bash: |
      git push --progress --prune git@github.com:hoooowsh/LifeRec-Categories.git \
        +refs/remotes/origin/*:refs/heads/*
    displayName: 'Copy to Github'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')