trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

jobs:
- job: Build
  steps:
  - checkout: self
    persistCredentials: true

  - bash: |
      git push git@github.com:hoooowsh/LifeRec-Categories.git \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
    displayName: 'Copy to Github'
