trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

steps:
- bash: |
    git push https://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@github.com/hoooowsh/LifeRec-Categories \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Github'
