trigger:
  branches:
    include:
      - main

pool:
  name: Agent-Sheng

steps:
- checkout: self
- bash: |
    git push --prune https://hoooowsh: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@github.com/hoooowsh/LifeRec-Categories.git \
        +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Push to GitHub'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  env:
    GITHUB_TOKEN: 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